// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/order/order.proto

package pbOrder

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Order service

func NewOrderEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Order service

type OrderService interface {
	CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*OperateResult, error)
	QueryOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*ListQueryOrder, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) CreateOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*OperateResult, error) {
	req := c.c.NewRequest(c.name, "Order.CreateOrder", in)
	out := new(OperateResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) QueryOrder(ctx context.Context, in *OrderInfo, opts ...client.CallOption) (*ListQueryOrder, error) {
	req := c.c.NewRequest(c.name, "Order.QueryOrder", in)
	out := new(ListQueryOrder)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	CreateOrder(context.Context, *OrderInfo, *OperateResult) error
	QueryOrder(context.Context, *OrderInfo, *ListQueryOrder) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		CreateOrder(ctx context.Context, in *OrderInfo, out *OperateResult) error
		QueryOrder(ctx context.Context, in *OrderInfo, out *ListQueryOrder) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) CreateOrder(ctx context.Context, in *OrderInfo, out *OperateResult) error {
	return h.OrderHandler.CreateOrder(ctx, in, out)
}

func (h *orderHandler) QueryOrder(ctx context.Context, in *OrderInfo, out *ListQueryOrder) error {
	return h.OrderHandler.QueryOrder(ctx, in, out)
}
